version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: banking_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb+srv://minibank:minibank@message.chxn5ja.mongodb.net/minibank?retryWrites=true&w=majority&appName=MESSAGE
      - JWT_SECRET=your-secret-key-change-in-production
      - JWT_EXPIRATION=24h
      - PORT=3001
      - NODE_ENV=production
      - USD_TO_EUR_RATE=0.92
    networks:
      - banking_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: banking_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - banking_network

networks:
  banking_network:
    driver: bridge
