services:
  mongodb:
    image: mongo:8.0
    container_name: banking_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: banking_platform
    volumes:
      - mongodb_data:/data/db
    networks:
      - banking_network

networks:
  banking_network:
    driver: bridge

volumes:
  mongodb_data:
