services:
  postgres:
    image: postgres:16-alpine
    container_name: minibank_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=minibank
      - POSTGRES_USER=minibank
      - POSTGRES_PASSWORD=minibank123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banking_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: minibank_pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@minibank.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    depends_on:
      - postgres
    networks:
      - banking_network

networks:
  banking_network:
    driver: bridge

volumes:
  postgres_data:
