services:
  # Backend API Service
  - type: web
    name: minibank-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 24h
      - key: USD_TO_EUR_RATE
        value: 0.92
      - key: FRONTEND_URL
        value: https://minibankplat.vercel.app

databases:
  # PostgreSQL Database
  - name: minibank-postgres
    databaseName: minibank
    user: minibank
    plan: free
